# Generated by Django 6.0.3 on 2026-03-06 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('building_blocks', 'Building Blocks'), ('iron_rods', 'Iron Rods'), ('plaster', 'Plaster'), ('paint_colour', 'Paint/Colour')], max_length=50)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('piece', 'Piece'), ('bar', 'Bar'), ('bucket', 'Bucket')], max_length=20)),
                ('commission_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('delivery_capacity_units_per_day', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_area', models.CharField(max_length=255)),
                ('delivery_address_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('subtotal_hardware', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='core.hardwarestore')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('building_blocks', 'Building Blocks'), ('iron_rods', 'Iron Rods'), ('plaster', 'Plaster'), ('paint_colour', 'Paint/Colour')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('piece', 'Piece'), ('bar', 'Bar'), ('bucket', 'Bucket')], max_length=20)),
                ('specs_json', models.JSONField(blank=True, null=True)),
                ('hardware_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_units', models.IntegerField(default=0)),
                ('delivery_eta_hours', models.IntegerField(default=24)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.hardwarestore')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_units', models.IntegerField()),
                ('hardware_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('fundi', 'Fundi'), ('hardware', 'Hardware Store'), ('admin', 'Admin')], default='fundi', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='fundi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.profile'),
        ),
        migrations.AddField(
            model_name='hardwarestore',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_stores', to='core.profile'),
        ),
    ]
