# Generated by Django 6.0.3 on 2026-03-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hardwarestore_address_hardwarestore_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Add details like dimensions, materials, color, etc.', null=True),
        ),
    ]
